name: apikicker
description: API の動作確認用プロジェクト

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.2
  cloud_functions: ^4.0.1

  another_flushbar: ^1.10.29

  like_button: ^2.0.4

  provider: ^6.0.3
  flutter_riverpod: ^1.0.3

  flutter_native_splash: ^2.2.10

  timeago: ^3.3.0

  flutter_launcher_icons: ^0.10.0

  firebase_messaging: ^14.2.2

  cached_network_image: ^3.2.3

  image_picker: ^0.8.6+2

  firebase_storage: ^11.0.14

  camera: ^0.10.3+2
  path_provider: ^2.0.13
  path: ^1.8.2

  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icon_image/
    - images/header/
    - images/splash/
    - images/button/
    - images/app_icon/

flutter_native_splash:
  image: "images/splash/splash_island_logo.png"
  color: "FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon/island_app_icon.png"
