name: apikicker
description: API の動作確認用プロジェクト

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  cloud_functions: ^3.3.6

  another_flushbar: ^1.10.29

  like_button: ^2.0.4

  provider: ^6.0.3
  flutter_riverpod: ^1.0.3

  flutter_native_splash: ^2.2.10

  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icon_image/
    - images/header/
    - images/splash/
    - images/button/

flutter_native_splash:
  image: "images/splash/splash_island_logo.png"
  color: "FFFFFF"
